// examples/laravel-11-vue/resources/js/nexus/(global)/(auth)/error.vue
<script setup>
import ErrorBoundary from "@/components/ErrorBoundary.vue";

const doSomething = () => {
  // window.location.reload();
  
};

</script>
<template>
  <ErrorBoundary :onError="doSomething">
    <slot></slot>

    <template v-slot:fallback>
      <span>Something went wrong... Oopsie daisy</span>
    </template>
    
  </ErrorBoundary>
</template>

// examples/laravel-11-react/resources/js/nexus/(global)/(auth)/error.jsx
import ErrorBoundary from "@/components/ErrorBoundary";


export default ({ children, onError }) => {
  const doSomething = () => {
    // window.location.reload();
  };

  return (
    <ErrorBoundary onError={doSomething} fallback={<span>Something went wrong... Oopsie daisy</span>}>
      {children}
    </ErrorBoundary>
  );
}
