// starter-kits/vue/resources/js/nexus/(guest)/reset-password/{token}/page.vue
<script setup lang="ts">
import InputError from '@/components/InputError.vue';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import AuthLayout from '@/layouts/AuthLayout.vue';
import { Head, visit } from '@laravext/vue3';
import { LoaderCircle } from 'lucide-vue-next';
import {inject} from 'vue';
import { useForm } from '@/composables/useForm';
import axios from 'axios';
const routeParams = inject('$routeParams') as any;
const queryParams = inject('$queryParams') as any;

const { data, processing, setProcessing, errors, setErrors, reset } = useForm({
    token: routeParams().token,
    email: queryParams().email,
    password: '',
    password_confirmation: '',
});

const submit = () => {
    setProcessing(true);

    axios
        .post('/api/reset-password', data.value)
        .then((response) => {
            reset();
            setErrors({});
            visit(route("login"));
        })
        .catch((error) => {
            setErrors(error.response.data.errors);
        })
        .finally(() => {
            setProcessing(false);
        });
};
</script>

<template>
    <AuthLayout title="Reset password" description="Please enter your new password below">
        <Head title="Reset password" />

        <form @submit.prevent="submit">
            <div class="grid gap-6">
                <div class="grid gap-2">
                    <Label for="email">Email</Label>
                    <Input id="email" type="email" name="email" autocomplete="email" v-model="data.email" class="mt-1 block w-full" readonly />
                    <InputError :message="errors.email" class="mt-2" />
                </div>

                <div class="grid gap-2">
                    <Label for="password">Password</Label>
                    <Input
                        id="password"
                        type="password"
                        name="password"
                        autocomplete="new-password"
                        v-model="data.password"
                        class="mt-1 block w-full"
                        autofocus
                        placeholder="Password"
                    />
                    <InputError :message="errors.password" />
                </div>

                <div class="grid gap-2">
                    <Label for="password_confirmation"> Confirm Password </Label>
                    <Input
                        id="password_confirmation"
                        type="password"
                        name="password_confirmation"
                        autocomplete="new-password"
                        v-model="data.password_confirmation"
                        class="mt-1 block w-full"
                        placeholder="Confirm password"
                    />
                    <InputError :message="errors.password_confirmation" />
                </div>

                <Button type="submit" class="mt-4 w-full" :disabled="processing">
                    <LoaderCircle v-if="processing" class="h-4 w-4 animate-spin" />
                    Reset password
                </Button>
            </div>
        </form>
    </AuthLayout>
</template>

// starter-kits/react/resources/js/nexus/(guest)/reset-password/{token}/page.tsx
import { LoaderCircle } from 'lucide-react';
import { FormEventHandler } from 'react';

import InputError from '@/components/input-error';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useForm } from '@/hooks/useForm';
import AuthLayout from '@/layouts/auth-layout';
import { Head, queryParams, routeParams, visit } from '@laravext/react';
import axios from 'axios';

export default function ResetPassword() {
    const { token } = routeParams();
    const { email } = queryParams();

    const { data, setData, processing, setProcessing, errors, setErrors, reset } = useForm({
        token: token,
        email: email,
        password: 'password',
        password_confirmation: 'password',
    });

    const submit: FormEventHandler = (e) => {
        e.preventDefault();
        setProcessing(true);

        axios
            .post('/api/reset-password', data)
            .then((response) => {
                reset();
                setErrors({});
                visit(route("login"));
            })
            .catch((error) => {
                setErrors(error.response.data.errors);
            })
            .finally(() => {
                setProcessing(false);
            });
    };

    return (
        <AuthLayout title="Reset password" description="Please enter your new password below">
            <Head title="Reset password" />

            <form onSubmit={submit}>
                <div className="grid gap-6">
                    <div className="grid gap-2">
                        <Label htmlFor="email">Email</Label>
                        <Input
                            id="email"
                            type="email"
                            name="email"
                            autoComplete="email"
                            value={data.email}
                            className="mt-1 block w-full"
                            readOnly
                            onChange={(e) => setData('email', e.target.value)}
                        />
                        <InputError message={errors.email} className="mt-2" />
                    </div>

                    <div className="grid gap-2">
                        <Label htmlFor="password">Password</Label>
                        <Input
                            id="password"
                            type="password"
                            name="password"
                            autoComplete="new-password"
                            value={data.password}
                            className="mt-1 block w-full"
                            autoFocus
                            onChange={(e) => setData('password', e.target.value)}
                            placeholder="Password"
                        />
                        <InputError message={errors.password} />
                    </div>

                    <div className="grid gap-2">
                        <Label htmlFor="password_confirmation">Confirm password</Label>
                        <Input
                            id="password_confirmation"
                            type="password"
                            name="password_confirmation"
                            autoComplete="new-password"
                            value={data.password_confirmation}
                            className="mt-1 block w-full"
                            onChange={(e) => setData('password_confirmation', e.target.value)}
                            placeholder="Confirm password"
                        />
                        <InputError message={errors.password_confirmation} className="mt-2" />
                    </div>

                    <Button type="submit" className="mt-4 w-full" disabled={processing}>
                        {processing && <LoaderCircle className="h-4 w-4 animate-spin" />}
                        Reset password
                    </Button>
                </div>
            </form>
        </AuthLayout>
    );
}
