// starter-kits/vue/resources/js/nexus/(global)/(auth)/dashboard/page.vue
<script setup>
import Header from '@/components/Header.vue';

</script>
<template>
    <Header>Dashboard</Header>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</template>

// starter-kits/react/resources/js/nexus/(global)/(auth)/dashboard/page.jsx
import { Head } from '@laravext/react';
import Header from '@/components/Header';

export default () => {
    return (
        <>
            <Head title="Dashboard" />
            
            <Header>Dashboard</Header>

            <div className="py-12">
                <div className="max-w-7xl mx-auto sm:px-6 lg:px-8">
                    <div className="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                        <div className="p-6 text-gray-900">
                            You're logged in!
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
};
