// examples/laravel-10-vue/resources/js/strands/PrivacyToggle.vue
<script setup>
import { privacy } from '@/composables/usePrivacy'
import axios from 'axios';
const {initialState, laravext} = defineProps(['initialState', 'laravext'])

if(initialState !== undefined) {
    privacy.setActive(initialState)
}

const handleToggle = () => {
    privacy.toggle();

    axios.put('/api/auth/user/privacy', {
        privacy: privacy.active
    });
}

</script>
<template>
    <span @click="handleToggle" class="cursor-pointer">
        {{ privacy.active ? 'Click to Turn Privacy Off' : 'Click to Turn Privacy On' }}
    </span>
</template>

// examples/laravel-10-react/resources/js/strands/PrivacyToggle.jsx
import usePrivacy from '@/hooks/usePrivacy'
import axios from 'axios';
import { useEffect } from 'react'

export default ({ laravext, initialState }) => {
    const { active, setActive, toggle } = usePrivacy();
    
    useEffect(() => {
        if(initialState !== undefined){
            setActive(initialState);
        }
    }, [initialState]);

    const handleToggle = () => {
        let currentState = active;
        toggle();
        axios.put('/api/auth/user/privacy', { privacy: !currentState })
    }

    return (
        <>
            <span className="cursor-pointer" onClick={handleToggle}>{active ? 'Click to Turn Privacy Off' : 'Click to Turn Privacy On'}</span>
        </>
    )
}
