// starter-kits/vue/resources/js/nexus/(global)/(guest)/layout.vue
<script setup>
import ApplicationLogo from '@/components/ApplicationLogo.vue';
import { Link } from '@laravext/vue3';
</script>

<template>
    <div class="min-h-screen flex flex-col sm:justify-center items-center pt-6 sm:pt-0 bg-gray-100">
        <div>
            <Link href="/">
                <ApplicationLogo class="w-20 h-20 fill-current text-gray-500" />
            </Link>
        </div>

        <div
            class="w-full sm:max-w-md mt-6 px-6 py-4 bg-white shadow-md overflow-hidden sm:rounded-lg"
        >
            <slot />
        </div>
    </div>
</template>

// starter-kits/react-ts/resources/js/nexus/(global)/(guest)/layout.tsx
import { Link, sharedProps } from "@laravext/react";
import ApplicationLogo from "@/components/ApplicationLogo";
import { PropsWithChildren } from "react";

export default ({children}: PropsWithChildren) => {
    const {user} = sharedProps();

    return (
        <div className="min-h-screen flex flex-col sm:justify-center items-center pt-6 sm:pt-0 bg-gray-100">
            <div>
                <Link href="/">
                    <ApplicationLogo className="w-20 h-20 fill-current text-gray-500" />
                </Link>
            </div>

            <div className="w-full sm:max-w-md mt-6 px-6 py-4 bg-white shadow-md overflow-hidden sm:rounded-lg">
                {children}
            </div>
        </div>
    );
};
