// starter-kits/vue/resources/js/components/AppShell.vue
<script setup lang="ts">
import { SidebarProvider } from '@/components/ui/sidebar';
import { onMounted, ref } from 'vue';
import Cookies from "js-cookie";

interface Props {
    variant?: 'header' | 'sidebar';
}

defineProps<Props>();

const isOpen = ref(true);

onMounted(() => {
    isOpen.value = Cookies.get('sidebar') === 'false';
});

const handleSidebarChange = (open: boolean) => {
    isOpen.value = open;
    Cookies.set('sidebar', String(open));
};
</script>

<template>
    <div v-if="variant === 'header'" class="flex min-h-screen w-full flex-col">
        <slot />
    </div>
    <SidebarProvider v-else :default-open="isOpen" :open="isOpen" @update:open="handleSidebarChange">
        <slot />
    </SidebarProvider>
</template>

// starter-kits/react-ts/resources/js/components/app-shell.tsx
import { SidebarProvider } from '@/components/ui/sidebar';
import { laravext } from '@laravext/react';
import Cookies from 'js-cookie';
import { useState } from 'react';

interface AppShellProps {
    children: React.ReactNode;
    variant?: 'header' | 'sidebar';
}

export function AppShell({ children, variant = 'header' }: AppShellProps) {
    const {sidebar_is_open} = laravext().app;
    const [isOpen, setIsOpen] = useState(() => (typeof window !== 'undefined' ? (Cookies.get('sidebar') ?? 'true') === 'true' : sidebar_is_open));

    const handleSidebarChange = (open: boolean) => {
        setIsOpen(open);

        if (typeof window !== 'undefined') {
            Cookies.set('sidebar', String(open));
        }
    };

    if (variant === 'header') {
        return <div className="flex min-h-screen w-full flex-col">{children}</div>;
    }

    return (
        <SidebarProvider defaultOpen={isOpen} open={isOpen} onOpenChange={handleSidebarChange}>
            {children}
        </SidebarProvider>
    );
}
