// examples/laravel-11-react/resources/js/components/Link.jsx
import { visit } from '@laravext/react/router';

export default  ({ routeName, href, className = '', children }) => {

  

  let resolvedHref = href ? href : (routeName && route().has(routeName) ? route(routeName) : '');

  return (
    <a href={resolvedHref} onClick={(e) =>{
      e.preventDefault();
      visit(resolvedHref);
    }

    } className={className}>
      {children}
    </a>
  );
};

// examples/laravel-11-vue/resources/js/components/Link.vue
<script setup>
import { visit } from '@laravext/vue/router';
import { Link } from '@laravext/vue'

const props = defineProps({
    routeName: {
        type: String,
        required: false,
    },
    href: {
        type: String,
        required: false,
    },
    classes: {
        type: String,
        required: false,
    },
});

let href = props.href ? props.href : (props.routeName && route().has(props.routeName) ? route(props.routeName) : '');
let classes = props.classes ?? '';

</script>

<template>
    <Link
        :href="href"
        :class="classes"
    >
        <slot />
    </Link>
</template>
