// examples/laravel-10-react/resources/js/nexus/error.jsx
import ErrorBoundary from "@/components/ErrorBoundary"

export default ({ laravext, children }) => {

    const doSomething = async () => {
        window.location.reload();
    }

    return (
        <ErrorBoundary onError={doSomething} fallback={<div>Something went wrong... Oopsie daisy</div>}>
            {children}
        </ErrorBoundary>
    )
}

// examples/laravel-10-vue/resources/js/nexus/(app)/error.vue
<script setup>
import ErrorBoundary from "@/components/ErrorBoundary.vue";

const doSomething = () => {
  window.location.reload();
};

</script>
<template>
  <ErrorBoundary :onError="doSomething">
    <slot></slot>

    <template v-slot:fallback>
      <span>Something went wrong... Oopsie daisy</span>
    </template>
    
  </ErrorBoundary>
</template>
