// examples/laravel-10-vue/resources/js/nexus/(global)/(auth)/admin/teams/{team}/page.vue
<script setup>
import DangerButton from '@/components/DangerButton.vue';
import Header from '@/components/Header.vue';
import Link from '@/components/Link.vue';
import Loading from '@/components/Loading.vue';
import PageContent from '@/components/PageContent.vue';
import PrimaryButton from '@/components/PrimaryButton.vue';
import { privacy } from '@/composables/usePrivacy';
import { routeParams } from '@laravext/vue';
import axios from 'axios';
import { reactive, onMounted, inject } from 'vue';
import { useI18n } from 'vue-i18n';
const { t } = useI18n();
const swal = inject('$swal')

const team = reactive({
    data: {
    },
    loading: true,
});


const destroyResource = (id) => {
    swal({
        Title: t('Are you sure?'),
        icon: 'warning',
        confirmButtonText: t('Yes, delete it!'),
        cancelButtonText: t('No, cancel!'),
        confirmButtonColor: '#d33',
        cancelButtonColor: '#3085d6',
        showCancelButton: true,
        showCloseButton: true,

    })
        .then((result) => {
            if (result.isConfirmed) {
                axios.delete(`/api/teams/${id}`)
                    .then(() => {
                        swal(t('Record deleted!'), t('The team has been deleted.'), 'success').then(() => {
                            window.location.href = '/admin/teams';
                        });
                    })
                    .catch(error => {
                        console.error(error);
                        swal(t('Error!'), t('An error occurred while deleting the team.'), 'error');
                    });
            }
        });
}

onMounted(() => {
    team.loading = true;

    axios.get(`/api/teams/${routeParams().team}`)
        .then(response => {
            team.data = {
                id: response.data.id,
                name: response.data.name,
                developers: response.data.developers,
            };

            team.loading = false;
        });
});

</script>
<template>
    <Header>{{ team.loading ? $t('Loading...') : `#${team.data.id} - ${team.data.name}` }}</Header>
    <div class="mt-3 mx-4 flex justify-end space-x-2">
        <Link :href="`/admin/teams/${routeParams().team}/edit`">
        <PrimaryButton>{{ $t('Edit') }}</PrimaryButton>
        </Link>

        <DangerButton @click="destroyResource(routeParams().team)" class="hover:text-red-900">{{ $t('Delete') }}</DangerButton>
    </div>
    <Loading v-if="team.loading" />
    <PageContent v-else>
        <Link :href="`/admin/teams/${routeParams().team}/projects`" class="text-blue-600 text-xl font-bold">{{ $t('Click to view projects of Team') }} #{{
            routeParams().team }}</Link>
        <br>
        <span class="text-lg font-bold">{{$t('Name')}}: </span>{{ team.data.name }}
        <br>
        <span class="text-lg font-bold">{{ $t('Developers') }}:</span>
        <div class="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 gap-4 p-4">
            <div class="bg-white rounded-lg shadow p-4" v-for="developer in team.data.developers.sort((a, b) => a.name.localeCompare(b.name))" :key="developer.id">
                <div class="font-bold">@{{ developer.username }}</div>
                <div class="border-b-2 border-gray-200 my-2"></div>
                <div class="text-sm">{{$t('Name')}}: {{ $t(developer.name) }}</div>
                <div class="text-sm">{{$t('Role')}}: {{ $t(developer.role_label) }}</div>
                <div class="text-sm">Email: {{ privacy.active ? '***@***' : developer.email }}</div>
            </div>
        </div>

    </PageContent>
</template>

// examples/laravel-11-react/resources/js/nexus/(global)/(auth)/admin/teams/{team}/page.jsx
import React, { useEffect, useState, useContext } from 'react';
import axios from 'axios';
import usePrivacy from '@/hooks/usePrivacy'
import { useTranslation } from 'react-i18next';
import { routeParams } from '@laravext/react';
import Swal from 'sweetalert2';
import DangerButton from '@/components/DangerButton';
import Header from '@/components/Header';
import Link from '@/components/Link';
import Loading from '@/components/Loading';
import PageContent from '@/components/PageContent';
import PrimaryButton from '@/components/PrimaryButton';

const TeamPage = () => {
  const { t } = useTranslation();
  const { setActive: setPrivacyActive, active: privacyIsActive, toggle: togglePrivacy } = usePrivacy();

  const [teamData, setTeamData] = useState({
    data: {},
    loading: true,
  });

  useEffect(() => {
    setTeamData({ ...teamData, loading: true });

    axios.get(`/api/teams/${routeParams().team}`)
      .then(response => {
        setTeamData({
          data: {
            id: response.data.id,
            name: response.data.name,
            developers: response.data.developers,
          },
          loading: false,
        });
      });
  }, []);

  const destroyResource = (id) => {
    Swal.fire({
      title: t('Are you sure?'),
      icon: 'warning',
      confirmButtonText: t('Yes, delete it!'),
      cancelButtonText: t('No, cancel!'),
      confirmButtonColor: '#d33',
      cancelButtonColor: '#3085d6',
      showCancelButton: true,
      showCloseButton: true,
    })
      .then((result) => {
        if (result.isConfirmed) {
          axios.delete(`/api/teams/${id}`)
            .then(() => {
              Swal.fire(t('Record deleted!'), t('The team has been deleted.'), 'success').then(() => {
                window.location.href = '/admin/teams';
              });
            })
            .catch(error => {
              console.error(error);
              Swal.fire(t('Error!'), t('An error occurred while deleting the team.'), 'error');
            });
        }
      });
  };

  return (
    <>
      <Header>{teamData.loading ? t('Loading...') : `#${teamData.data.id} - ${teamData.data.name}`}</Header>
      <div className="mt-3 mx-4 flex justify-end space-x-2">
        <Link href={`/admin/teams/${routeParams().team}/edit`}>
          <PrimaryButton>{t('Edit')}</PrimaryButton>
        </Link>

        <DangerButton onClick={() => destroyResource(routeParams().team)} className="hover:text-red-900">
          {t('Delete')}
        </DangerButton>
      </div>
      {teamData.loading ? (
        <Loading />
      ) : (
        <PageContent>
          <Link href={`/admin/teams/${routeParams().team}/projects`} className="text-blue-600 text-xl font-bold">
            {t('Click to view projects of Team')} #{routeParams().team}
          </Link>
          <br />
          <span className="text-lg font-bold">{t('Name')}: </span>{teamData.data.name}
          <br />
          <span className="text-lg font-bold">{t('Developers')}:</span>
          <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 gap-4 p-4">
            {teamData.data.developers.sort((a, b) => a.name.localeCompare(b.name)).map(developer => (
              <div className="bg-white rounded-lg shadow p-4" key={developer.id}>
                <div className="font-bold">@{developer.username}</div>
                <div className="border-b-2 border-gray-200 my-2"></div>
                <div className="text-sm">{t('Name')}: {t(developer.name)}</div>
                <div className="text-sm">{t('Role')}: {t(developer.role_label)}</div>
                <div className="text-sm">Email: {privacyIsActive ? '***@***' : developer.email}</div>
              </div>
            ))}
          </div>
        </PageContent>
      )}
    </>
  );
};

export default TeamPage;
