// examples/laravel-10-vue/resources/js/nexus/(global)/(guest)/our-teams/page.vue
<script setup>
import { Head, nexusProps } from '@laravext/vue'

const { teams } = nexusProps();

</script>
<template>
    <Head title="Our Teams" />
    <div class="flex justify-center items-center min-h-[70vh] mt-6">
        <div>
            <h3 class="text-2xl mb-2">Our teams...</h3>
            <ul>
                <li v-for="team in teams" :key="team.id">
                    {{ team.name }}
                </li>
            </ul>
        </div>
    </div>
</template>

// examples/laravel-11-react/resources/js/nexus/(global)/(guest)/our-teams/page.jsx
import {Head, nexusProps} from '@laravext/react'

export default () => {
  const { teams } = nexusProps();

  return (
    <div>
        <Head>Our Teams</Head>
      <div className="flex justify-center items-center min-h-[70vh] mt-6">
        <div>
          <h3 className="text-2xl mb-2">Our teams...</h3>
          <ul>
            {teams.map(team => (
              <li key={team.id}>
                {team.name}
              </li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  );
};
