// starter-kits/react-ts/resources/js/nexus/(global)/(guest)/register/page.tsx
import { FormEvent, useState } from "react";
import InputError from "@/components/InputError";
import InputLabel from "@/components/InputLabel";
import PrimaryButton from "@/components/PrimaryButton";
import TextInput from "@/components/TextInput";
import { Head, Link, visit } from "@laravext/react";
import axios from "axios";
import { route } from "ziggy-js";

export default () => {
    const [data, setData] = useState({
        name: "",
        email: "",
        password: "",
        password_confirmation: "",
    });

    const [errors, setErrors] = useState({
        name: "",
        email: "",
        password: "",
        password_confirmation: "",
    });
    const [processing, setProcessing] = useState(false);

    const submit = (e: FormEvent) => {
        e.preventDefault();

        setProcessing(true);
        axios
            .post("/api/auth/register", data)
            .then(() => {
                visit("/dashboard");
            })
            .catch((error) => {
                setProcessing(false);
                if (error.response.status === 422) {
                    setErrors(error.response.data.errors);
                } else {
                    console.error(error);
                }
            });
    };

    return (
        <>
            <Head title="Register" />

            <form onSubmit={submit}>
                <div>
                    <InputLabel htmlFor="name" value="Name" />

                    <TextInput
                        id="name"
                        name="name"
                        value={data.name}
                        className="mt-1 block w-full"
                        autoComplete="name"
                        isFocused={true}
                        onChange={(e) =>
                            setData((prev) => ({
                                ...prev,
                                name: e.target.value,
                            }))
                        }
                        required
                    />

                    <InputError message={errors.name} className="mt-2" />
                </div>

                <div className="mt-4">
                    <InputLabel htmlFor="email" value="Email" />

                    <TextInput
                        id="email"
                        type="email"
                        name="email"
                        value={data.email}
                        className="mt-1 block w-full"
                        autoComplete="username"
                        onChange={(e) =>
                            setData((prev) => ({
                                ...prev,
                                email: e.target.value,
                            }))
                        }
                        required
                    />

                    <InputError message={errors.email} className="mt-2" />
                </div>

                <div className="mt-4">
                    <InputLabel htmlFor="password" value="Password" />

                    <TextInput
                        id="password"
                        type="password"
                        name="password"
                        value={data.password}
                        className="mt-1 block w-full"
                        autoComplete="new-password"
                        onChange={(e) =>
                            setData((prev) => ({
                                ...prev,
                                password: e.target.value,
                            }))
                        }
                        required
                    />

                    <InputError message={errors.password} className="mt-2" />
                </div>

                <div className="mt-4">
                    <InputLabel
                        htmlFor="password_confirmation"
                        value="Confirm Password"
                    />

                    <TextInput
                        id="password_confirmation"
                        type="password"
                        name="password_confirmation"
                        value={data.password_confirmation}
                        className="mt-1 block w-full"
                        autoComplete="new-password"
                        onChange={(e) =>
                            setData((prev) => ({
                                ...prev,
                                password_confirmation: e.target.value,
                            }))
                        }
                        required
                    />

                    <InputError
                        message={errors.password_confirmation}
                        className="mt-2"
                    />
                </div>

                <div className="flex items-center justify-end mt-4">
                    <Link
                        href={route("login")}
                        className="underline text-sm text-gray-600 hover:text-gray-900 rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                    >
                        Already registered?
                    </Link>

                    <PrimaryButton className="ms-4" disabled={processing}>
                        Register
                    </PrimaryButton>
                </div>
            </form>
        </>
    );
};

// starter-kits/vue-ts/resources/js/nexus/(global)/(guest)/register/page.vue
<script setup>
import { ref, reactive } from "vue";
import InputError from "@/components/InputError.vue";
import InputLabel from "@/components/InputLabel.vue";
import PrimaryButton from "@/components/PrimaryButton.vue";
import TextInput from "@/components/TextInput.vue";
import { Head, Link, visit } from "@laravext/vue3";
import axios from "axios";

const data = reactive({
  name: "",
  email: "",
  password: "",
  password_confirmation: "",
});

const errors = ref({});

const processing = ref(false);

const submit = () => {
  processing.value = true;
  axios
    .post("/api/auth/register", data)
    .then(() => {
      visit("/dashboard");
    })
    .catch((error) => {
      processing.value = false;
      if (error.response.status === 422) {
        errors.value = error.response.data.errors;
      } else {
        console.error(error);
      }
    });
};

</script>
<template>
  <div>
    <Head title="Register" />

    <form @submit.prevent="submit">
      <div>
        <InputLabel for="name" :value="'Name'" />

        <TextInput
          id="name"
          v-model="data.name"
          class="mt-1 block w-full"
          autocomplete="name"
          :is-focused="true"
          required
        />

        <InputError :message="errors.name" class="mt-2" />
      </div>

      <div class="mt-4">
        <InputLabel for="email" :value="'Email'" />

        <TextInput
          id="email"
          type="email"
          v-model="data.email"
          class="mt-1 block w-full"
          autocomplete="username"
          required
        />

        <InputError :message="errors.email" class="mt-2" />
      </div>

      <div class="mt-4">
        <InputLabel for="password" :value="'Password'" />

        <TextInput
          id="password"
          type="password"
          v-model="data.password"
          class="mt-1 block w-full"
          autocomplete="new-password"
          required
        />

        <InputError :message="errors.password" class="mt-2" />
      </div>

      <div class="mt-4">
        <InputLabel for="password_confirmation" :value="'Confirm Password'" />

        <TextInput
          id="password_confirmation"
          type="password"
          v-model="data.password_confirmation"
          class="mt-1 block w-full"
          autocomplete="new-password"
          required
        />

        <InputError :message="errors.password_confirmation" class="mt-2" />
      </div>

      <div class="flex items-center justify-end mt-4">
        <Link
          :href="route('login')"
          class="underline text-sm text-gray-600 hover:text-gray-900 rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
        >
          Already registered?
        </Link>

        <PrimaryButton :class="'ms-4'" :disabled="processing">
          Register
        </PrimaryButton>
      </div>
    </form>
  </div>
</template>
