// examples/laravel-10-vue/resources/js/strands/PrivacyToggle.vue
<script setup>
import { privacy } from '@/composables/usePrivacy'
const props = defineProps(['initialState'])

if(props.initialState !== undefined) {
    privacy.setActive(props.initialState)
}

</script>
<template>
    <span @click="privacy.toggle" class="cursor-pointer">
        {{ privacy.active ? 'Click to Turn Privacy Off' : 'Click to Turn Privacy On' }}
    </span>
</template>

// examples/laravel-10/resources/js/strands/PrivacyToggle.jsx
import usePrivacy from '@/hooks/usePrivacy'

export default ({laravext}) => {
    const { active, toggle } = usePrivacy();

    return (
        <>
            <button className="cursor-pointer"  onClick={toggle}>{active ? 'Click to Turn Privacy Off' : 'Click to Turn Privacy On'}</button>
        </>

    )
}
