// starter-kits/react-ts/resources/js/nexus/(global)/(guest)/login/page.tsx
import Checkbox from '@/components/Checkbox';
import InputError from '@/components/InputError';
import InputLabel from '@/components/InputLabel';
import PrimaryButton from '@/components/PrimaryButton';
import TextInput from '@/components/TextInput';
import { Head, Link, visit } from '@laravext/react';
import axios from 'axios';
import { FormEvent, useState } from 'react';
import { route } from 'ziggy-js';

export default () => {
    const [data, setData] = useState({
        email: '',
        password: '',
        remember: false,
    });

    const [processing, setProcessing] = useState(false);
    const [errors, setErrors] = useState({
        email: '',
        password: '',
    });

    const submit = (e: FormEvent) => {
        e.preventDefault();

        axios.post('/api/auth/login', {
            email: data.email,
            password: data.password,
            remember: data.remember,
        }).then(() => {
            visit('/dashboard');
        }).catch((error) => {
            if (error.response.status === 422) {
                setErrors(error.response.data.errors);
            } else {
                console.error(error);
            }
        }); 
    };

    return (
        <>
            <Head title="Log in" />

            <form onSubmit={submit}>
                <div>
                    <InputLabel htmlFor="email" value="Email" />

                    <TextInput
                        id="email"
                        type="email"
                        name="email"
                        value={data.email}
                        className="mt-1 block w-full"
                        autoComplete="username"
                        isFocused={true}
                        onChange={(e) => setData((prev) => ({ ...prev, email: e.target.value }))}
                    />

                    <InputError message={errors.email} className="mt-2" />
                </div>

                <div className="mt-4">
                    <InputLabel htmlFor="password" value="Password" />

                    <TextInput
                        id="password"
                        type="password"
                        name="password"
                        value={data.password}
                        className="mt-1 block w-full"
                        autoComplete="current-password"
                        onChange={(e) => setData((prev) => ({ ...prev, password: e.target.value }))}
                    />

                    <InputError message={errors.password} className="mt-2" />
                </div>

                <div className="block mt-4">
                    <label className="flex items-center">
                        <Checkbox
                            name="remember"
                            checked={data.remember}
                            onChange={(e) => setData((prev) => ({ ...prev, remember: e.target.checked }))}
                        />
                        <span className="ms-2 text-sm text-gray-600">Remember me</span>
                    </label>
                </div>

                <div className="flex items-center justify-end mt-4 space-x-3">
                    
                    <Link
                        href={route('register')}
                        className="underline text-sm text-gray-600 hover:text-gray-900 rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                    >
                        Need an account?
                    </Link>

                    <Link
                        href={route('forgot-password')}
                        className="underline text-sm text-gray-600 hover:text-gray-900 rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                    >
                        Forgot your password?
                    </Link>

                    <PrimaryButton className="ms-4" disabled={processing}>
                        Log in
                    </PrimaryButton>
                </div>
            </form>
        </>
    );
}

// starter-kits/vue-ts/resources/js/nexus/(global)/(guest)/login/page.vue
<script setup>
import Checkbox from '@/components/Checkbox.vue';
import InputError from '@/components/InputError.vue';
import InputLabel from '@/components/InputLabel.vue';
import PrimaryButton from '@/components/PrimaryButton.vue';
import TextInput from '@/components/TextInput.vue';
import { Head, Link, visit } from '@laravext/vue3';
import axios from 'axios';
import { ref , reactive } from 'vue';

const data = reactive({
    email: '',
    password: '',
    remember: false,
});

const processing = ref(false);

const errors = ref({});

const submit = () => {
    processing.value = true;

    axios.post('/api/auth/login', {
            email: data.email,
            password: data.password,
            remember: data.remember,
        }).then(() => {
            visit('/dashboard');
        }).catch((error) => {
            processing.value = false;
            if (error.response.status === 422) {
                console.log(error.response.data.errors);
                errors.value = error.response.data.errors;
            } else {
                console.error(error);
            }
        }); 
};
</script>

<template>

    <Head title="Log in" />

    <div v-if="status" class="mb-4 font-medium text-sm text-green-600">
        {{ status }}
    </div>

    <form @submit.prevent="submit">
        <div>
            <InputLabel for="email" value="Email" />

            <TextInput id="email" type="email" class="mt-1 block w-full" v-model="data.email" required autofocus
                autocomplete="username" />

            <InputError class="mt-2" :message="errors.email" />
        </div>

        <div class="mt-4">
            <InputLabel for="password" value="Password" />

            <TextInput id="password" type="password" class="mt-1 block w-full" v-model="data.password" required
                autocomplete="current-password" />

            <InputError class="mt-2" :message="errors.password" />
        </div>

        <div class="block mt-4">
            <label class="flex items-center">
                <Checkbox name="remember" v-model:checked="data.remember" />
                <span class="ms-2 text-sm text-gray-600">Remember me</span>
            </label>
        </div>

        <div class="flex items-center justify-end space-x-3 mt-4">
            <Link :href="route('register')"
                class="underline text-sm text-gray-600 hover:text-gray-900 rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                Need an account?
            </Link>

            <Link :href="route('forgot-password')"
                class="underline text-sm text-gray-600 hover:text-gray-900 rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            Forgot your password?
            </Link>

            <PrimaryButton class="ms-4" :class="{ 'opacity-25': processing }" :disabled="processing">
                Log in
            </PrimaryButton>
        </div>
    </form>

</template>
