// starter-kits/react/resources/js/components/app-shell.tsx
import { SidebarProvider } from '@/components/ui/sidebar';
import { sharedProps } from '@laravext/react';
import Cookies from 'js-cookie';
import { useState } from 'react';

interface AppShellProps {
    children: React.ReactNode;
    variant?: 'header' | 'sidebar';
}

export function AppShell({ children, variant = 'header' }: AppShellProps) {
    const {sidebar} = sharedProps();;
    const [isOpen, setIsOpen] = useState(() => (sidebar === 'true'));

    const handleSidebarChange = (open: boolean) => {
        setIsOpen(open);

        if (typeof window !== 'undefined') {
            Cookies.set('sidebar', String(open));
        }
    };

    if (variant === 'header') {
        return <div className="flex min-h-screen w-full flex-col">{children}</div>;
    }

    return (
        <SidebarProvider defaultOpen={isOpen} open={isOpen} onOpenChange={handleSidebarChange}>
            {children}
        </SidebarProvider>
    );
}

// starter-kits/vue/resources/js/components/AppShell.vue
<script setup lang="ts">
import { SidebarProvider } from '@/components/ui/sidebar';
import { onMounted, ref, inject } from 'vue';
import Cookies from 'js-cookie';
const sharedProps = inject("$sharedProps") as any;

interface Props {
    variant?: 'header' | 'sidebar';
}

defineProps<Props>();

const isOpen = ref(sharedProps().sidebar === 'true');

onMounted(() => {
    isOpen.value = sharedProps().sidebar === 'true';
});

const handleSidebarChange = (open: boolean) => {
    isOpen.value = open;
    Cookies.set('sidebar', String(open));
};
</script>

<template>
    <div v-if="variant === 'header'" class="flex min-h-screen w-full flex-col">
        <slot />
    </div>
    <SidebarProvider v-else :default-open="isOpen" :open="isOpen" @update:open="handleSidebarChange">
        <slot />
    </SidebarProvider>
</template>
