// examples/laravel-10-vue/resources/js/components/ErrorBoundary.vue
<script setup>
import { onErrorCaptured, ref } from "vue";
const { onError } = defineProps(["onError"]);

let errorWasCaptured = ref(false);

onErrorCaptured((error, vm, info) => {
  errorWasCaptured.value = true;

  console.log("Error captured in error component: ", error);

  if (onError) {
    onError();
  }
});
</script>
<template>
  <slot name="default" v-if="!errorWasCaptured"></slot>
  <slot name="fallback" v-else></slot>
</template>

// examples/laravel-10-react/resources/js/components/ErrorBoundary.jsx
import React from 'react';

class ErrorBoundary extends React.Component {
    constructor(props) {
        super(props);
        this.state = { hasError: false };
    }

    static getDerivedStateFromError(error) {
        return { hasError: true };
    }

    componentDidCatch(error, info) {
        console.log('Error captured in error component: ', error)
        
        if(this.props.onError){
            this.props.onError();
        }
    }

    render() {
        if (this.state.hasError) {
            return this.props.fallback;
        }

        return this.props.children;
    }
}

export default ErrorBoundary;
