// starter-kits/react/resources/js/nexus/(global)/(auth)/profile/partials/UpdatePasswordForm.jsx
import { useRef, useState } from 'react';
import InputError from '@/components/InputError';
import InputLabel from '@/components/InputLabel';
import PrimaryButton from '@/components/PrimaryButton';
import TextInput from '@/components/TextInput';
import { Transition } from '@headlessui/react';
import axios from 'axios';

export default ({ className = '' }) => {
    const passwordInput = useRef();
    const currentPasswordInput = useRef();
    
    const [data, setData] = useState({
        current_password: '',
        password: '',
        password_confirmation: '',
    });

    const [errors, setErrors] = useState({
        current_password: '',
        password: '',
        password_confirmation: '',
    });

    const reset = () => {
        setData({
            current_password: '',
            password: '',
            password_confirmation: '',
        });

        setErrors({
            current_password: '',
            password: '',
            password_confirmation: '',
        });
    };

    const [processing, setProcessing] = useState(false);
    const [recentlySuccessful, setRecentlySuccessful] = useState(false);

    const updatePassword = (e) => {
        e.preventDefault();

        setProcessing(true);

        axios.put('/api/auth/password', data)
        .then(() => {
            setRecentlySuccessful(true);
            setProcessing(false);
            reset();
        }).catch((error) => {
            setErrors(error.response.data.errors);
            setProcessing(false);
        });
    };

    return (
        <section className={className}>
            <header>
                <h2 className="text-lg font-medium text-gray-900">Update Password</h2>

                <p className="mt-1 text-sm text-gray-600">
                    Ensure your account is using a long, random password to stay secure.
                </p>
            </header>

            <form onSubmit={updatePassword} className="mt-6 space-y-6">
                <div>
                    <InputLabel htmlFor="current_password" value="Current Password" />

                    <TextInput
                        id="current_password"
                        ref={currentPasswordInput}
                        value={data.current_password}
                        onChange={(e) => setData((prev) => ({ ...prev, current_password: e.target.value }))}
                        type="password"
                        className="mt-1 block w-full"
                        autoComplete="current-password"
                    />

                    <InputError message={errors.current_password} className="mt-2" />
                </div>

                <div>
                    <InputLabel htmlFor="password" value="New Password" />

                    <TextInput
                        id="password"
                        ref={passwordInput}
                        value={data.password}
                        onChange={(e) => setData((prev) => ({ ...prev, password: e.target.value }))}
                        type="password"
                        className="mt-1 block w-full"
                        autoComplete="new-password"
                    />

                    <InputError message={errors.password} className="mt-2" />
                </div>

                <div>
                    <InputLabel htmlFor="password_confirmation" value="Confirm Password" />

                    <TextInput
                        id="password_confirmation"
                        value={data.password_confirmation}
                        onChange={(e) => setData((prev) => ({ ...prev, password_confirmation: e.target.value }))}
                        type="password"
                        className="mt-1 block w-full"
                        autoComplete="new-password"
                    />

                    <InputError message={errors.password_confirmation} className="mt-2" />
                </div>

                <div className="flex items-center gap-4">
                    <PrimaryButton disabled={processing}>Save</PrimaryButton>

                    <Transition
                        show={recentlySuccessful}
                        enter="transition ease-in-out"
                        enterFrom="opacity-0"
                        leave="transition ease-in-out"
                        leaveTo="opacity-0"
                    >
                        <p className="text-sm text-gray-600">Saved.</p>
                    </Transition>
                </div>
            </form>
        </section>
    );
}

// starter-kits/vue/resources/js/nexus/(global)/(auth)/profile/partials/UpdatePasswordForm.vue
<script setup>
import InputError from '@/components/InputError.vue';
import InputLabel from '@/components/InputLabel.vue';
import PrimaryButton from '@/components/PrimaryButton.vue';
import TextInput from '@/components/TextInput.vue';
import axios from 'axios';
import { ref, reactive } from 'vue';

defineProps(['classes'])

const passwordInput = ref(null);
const currentPasswordInput = ref(null);

const data = reactive({
    current_password: '',
    password: '',
    password_confirmation: '',
});

const errors = ref({})
const processing = ref(false);
const recentlySuccessful = ref(false);

const updatePassword = () => {
    axios.put('/api/auth/password', data)
        .then(() => {
            recentlySuccessful.value = true;
            processing.value = false;
            data.current_password = '';
            data.password = '';
            data.password_confirmation = '';

            errors.value = {};
        })
        .catch((error) => {
            if (error.response.status === 422) {
                errors.value = error.response.data.errors;
            } else {
                console.error(error);
            }
            processing.value = false;
        });
};
</script>

<template>
    <section>
        <header>
            <h2 class="text-lg font-medium text-gray-900">Update Password</h2>

            <p class="mt-1 text-sm text-gray-600">
                Ensure your account is using a long, random password to stay secure.
            </p>
        </header>

        <form @submit.prevent="updatePassword" class="mt-6 space-y-6">
            <div>
                <InputLabel for="current_password" value="Current Password" />

                <TextInput id="current_password" ref="currentPasswordInput" v-model="data.current_password"
                    type="password" class="mt-1 block w-full" autocomplete="current-password" />

                <InputError :message="errors.current_password" class="mt-2" />
            </div>

            <div>
                <InputLabel for="password" value="New Password" />

                <TextInput id="password" ref="passwordInput" v-model="data.password" type="password"
                    class="mt-1 block w-full" autocomplete="new-password" />

                <InputError :message="errors.password" class="mt-2" />
            </div>

            <div>
                <InputLabel for="password_confirmation" value="Confirm Password" />

                <TextInput id="password_confirmation" v-model="data.password_confirmation" type="password"
                    class="mt-1 block w-full" autocomplete="new-password" />

                <InputError :message="errors.password_confirmation" class="mt-2" />
            </div>

            <div class="flex items-center gap-4">
                <PrimaryButton :disabled="processing">Save</PrimaryButton>

                <Transition enter-active-class="transition ease-in-out" enter-from-class="opacity-0"
                    leave-active-class="transition ease-in-out" leave-to-class="opacity-0">
                    <p v-if="recentlySuccessful" class="text-sm text-gray-600">Saved.</p>
                </Transition>
            </div>
        </form>
    </section>
</template>
