// examples/laravel-11-vue/resources/js/nexus/(global)/(guest)/our-projects/page.vue
<script setup>
import { Head } from '@laravext/vue'
import axios from 'axios';
import { reactive, onMounted } from 'vue'

const data = reactive({
    projects: [],
    loading: true,
});

onMounted(async () => {
    axios.get('/api/projects')
        .then(response => {
            data.projects = response.data.data;
            data.loading = false;
        })
        .catch(error => {
            console.error(error);
            data.loading = false;
        });
});

</script>
<template>
    <Head title="Our Projects" />
    <div v-if="data.loading" class="flex justify-center items-center min-h-[70vh] mt-6">
        Loading...
    </div>
    <div v-else class="flex justify-center items-center min-h-[70vh]  mt-6">

        <div>
            <h3 class="text-2xl mb-2">Our projects...</h3>
            <ul>
                <li v-for="project in data.projects" :key="project.id">
                    {{ project.name }}
                </li>
            </ul>
        </div>
    </div>
</template>

// examples/laravel-11-react/resources/js/nexus/(global)/(guest)/our-projects/page.jsx
import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { Head } from '@laravext/react';

export default () => {
    const [projects, setProjects] = useState([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        axios.get('/api/projects')
            .then(response => {
                setProjects(response.data.data);
                setLoading(false);
            })
            .catch(error => {
                console.error(error);
                setLoading(false);
            });
    }, []);

    return (
        <>
            <Head title="Our Projects" />
            {loading ? (
                <div className="flex justify-center items-center min-h-[70vh] mt-6">
                    Loading...
                </div>
            ) : (
                <div className="flex justify-center items-center min-h-[70vh] mt-6">
                    <div>
                        <h3 className="text-2xl mb-2">Our projects...</h3>
                        <ul>
                            {projects.map(project => (
                                <li key={project.id}>
                                    {project.name}
                                </li>
                            ))}
                        </ul>
                    </div>
                </div>
            )}
        </>
    );
};
