// examples/laravel-11-react/resources/js/components/Loading.jsx
import React from 'react';
const LoaderComponent = ({ condition = true }) => {
  return (
    <>
      {condition && (
        <div className="absolute inset-0 flex items-center justify-center">
          <div className="loader"></div>
        </div>
      )}
    </>
  );
};
export default LoaderComponent;

// examples/laravel-10-vue/resources/js/components/Loading.vue
<script setup>
const props = defineProps({
    condition: {
        type: Boolean,
        required: false,
        default: true,
    },
});

</script>

<template>
    <div v-if="props.condition" class="absolute inset-0 flex items-center justify-center">
        <div class="loader"></div>
    </div>
</template>
