// examples/laravel-10-react/resources/js/components/PageContent.jsx
export default ({ children }) => {
    return (
        <div>
            <div className="py-3">
                <div className="mx-auto sm:px-6 lg:px-4">
                    <div className="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg p-6 text-gray-900 dark:text-gray-100">
                        {children}
                    </div>
                </div>
            </div>
        </div>
    );
};

// examples/laravel-10-vue/resources/js/components/PageContent.vue
<template>
    <div>
        <div class="py-6">
            <div class="mx-auto sm:px-6 lg:px-4">
                <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg p-6 text-gray-900 dark:text-gray-100">
                    <slot />          
                </div>
            </div>
        </div>
    </div>
</template>
