// examples/laravel-11-react/resources/js/nexus/(global)/(guest)/layout.jsx
import { Link } from "@laravext/react";
import ApplicationLogo from "@/components/ApplicationLogo";

export default ({children}) => {
    return (
        <div className="min-h-[70vh] flex flex-col sm:justify-center items-center pt-6 sm:pt-0 bg-gray-100">

            <div className="w-full sm:max-w-md mt-6 px-6 py-4 bg-white shadow-md overflow-hidden sm:rounded-lg">
                {children}
            </div>
        </div>
    );
};

// starter-kits/vue/resources/js/nexus/(global)/(guest)/layout.vue
<script setup>
import ApplicationLogo from '@/components/ApplicationLogo.vue';
import { Link } from '@laravext/vue3';
</script>

<template>
    <div class="min-h-screen flex flex-col sm:justify-center items-center pt-6 sm:pt-0 bg-gray-100">
        <div>
            <Link href="/">
                <ApplicationLogo class="w-20 h-20 fill-current text-gray-500" />
            </Link>
        </div>

        <div
            class="w-full sm:max-w-md mt-6 px-6 py-4 bg-white shadow-md overflow-hidden sm:rounded-lg"
        >
            <slot />
        </div>
    </div>
</template>
