// starter-kits/react-ts/resources/js/nexus/(global)/(guest)/password-reset/{token}/page.tsx
import InputError from '@/components/InputError';
import InputLabel from '@/components/InputLabel';
import PrimaryButton from '@/components/PrimaryButton';
import TextInput from '@/components/TextInput';
import { Head, queryParams, routeParams, visit } from '@laravext/react';
import axios from 'axios';
import {FormEvent, useState} from 'react';
import { route } from 'ziggy-js';

export default ({ }) => {

    const { token } = routeParams();
    const { email } = queryParams();

    const [ data, setData ] = useState({
        token: token,
        email: email,
        password: '',
        password_confirmation: '',
    });

    const [ processing, setProcessing ] = useState(false);

    const [ errors, setErrors ] = useState({
        email: '',
        password: '',
        password_confirmation: '',
    });

    const submit = (e: FormEvent) => {
        e.preventDefault();

        axios.post('/api/auth/reset-password', data)
        .then(({ data }) => {
            visit(route('login'));
        }).catch((error) => {
            if(error.response.status === 422) {
                setErrors(error.response.data.errors);
            }

            setProcessing(false);
        });
    };

    return (
        <>
            <Head title="Reset Password" />

            <form onSubmit={submit}>
                <div>
                    <InputLabel htmlFor="email" value="Email" />

                    <TextInput
                        id="email"
                        type="email"
                        name="email"
                        value={data.email}
                        readOnly={true}
                        className="mt-1 block w-full"
                        autoComplete="username"
                        onChange={(e) => setData((prev) => ({ ...prev, email: e.target.value }))}
                    />

                    <InputError message={errors.email} className="mt-2" />
                </div>

                <div className="mt-4">
                    <InputLabel htmlFor="password" value="Password" />

                    <TextInput
                        id="password"
                        type="password"
                        name="password"
                        value={data.password}
                        className="mt-1 block w-full"
                        autoComplete="new-password"
                        isFocused={true}
                        onChange={(e) => setData((prev) => ({ ...prev, password: e.target.value }))}
                    />

                    <InputError message={errors.password} className="mt-2" />
                </div>

                <div className="mt-4">
                    <InputLabel htmlFor="password_confirmation" value="Confirm Password" />

                    <TextInput
                        type="password"
                        id="password_confirmation"
                        name="password_confirmation"
                        value={data.password_confirmation}
                        className="mt-1 block w-full"
                        autoComplete="new-password"
                        onChange={(e) => setData((prev) => ({ ...prev, password_confirmation: e.target.value }))}
                    />

                    <InputError message={errors.password_confirmation} className="mt-2" />
                </div>

                <div className="flex items-center justify-end mt-4">
                    <PrimaryButton className="ms-4" disabled={processing}>
                        Reset Password
                    </PrimaryButton>
                </div>
            </form>
        </>
    );
}

// starter-kits/vue-ts/resources/js/nexus/(global)/(guest)/password-reset/{token}/page.vue
<script setup>
import { inject, ref, reactive } from 'vue';
import InputError from '@/components/InputError.vue';
import InputLabel from '@/components/InputLabel.vue';
import PrimaryButton from '@/components/PrimaryButton.vue';
import TextInput from '@/components/TextInput.vue';
import { Head, visit } from '@laravext/vue3';
import axios from 'axios';

const $routeParams = inject('$routeParams');
const $queryParams = inject('$queryParams');

const { token } = $routeParams();
const { email } = $queryParams();

const data = reactive({
    token: token,
    email: email,
    password: '',
    password_confirmation: '',
});

const processing = ref(false);
const errors = ref({})

const submit = (e) => {
    e.preventDefault();
    processing.value = true;

    axios.post('/api/auth/reset-password', data)
        .then(({ data }) => {
            visit(route('login'));
        }).catch((error) => {
            if (error.response.status === 422) {
                errors.value = error.response.data.errors;
            }

            processing.value = false
        });
};

</script>
<template>

    <Head title="Reset Password" />

    <form @submit.prevent="submit">
        <div>
            <InputLabel htmlFor="email" value="Email" />

            <TextInput id="email" type="email" name="email" readOnly class="mt-1 block w-full"
                autoComplete="username" v-model="data.email" />

            <InputError :message="errors.email" class="mt-2" />
        </div>

        <div class="mt-4">
            <InputLabel htmlFor="password" value="Password" />

            <TextInput id="password" type="password" name="password" class="mt-1 block w-full"
                autoComplete="new-password" isFocused={true} v-model="data.password" />

            <InputError :message="errors.password" class="mt-2" />
        </div>

        <div class="mt-4">
            <InputLabel htmlFor="password_confirmation" value="Confirm Password" />

            <TextInput type="password" id="password_confirmation" name="password_confirmation"
                class="mt-1 block w-full" autoComplete="new-password" v-model="data.password_confirmation" />

            <InputError :message="errors.password_confirmation" class="mt-2" />
        </div>

        <div class="flex items-center justify-end mt-4">
            <PrimaryButton class="ms-4" :disabled="processing">
                Reset Password
            </PrimaryButton>
        </div>
    </form>
</template>
