// examples/laravel-11-react/resources/js/nexus/(global)/(auth)/admin/dashboard/page.jsx
import Header from '@/components/Header';
import PageContent from '@/components/PageContent';
import { sharedProps } from '@laravext/react'

export default () => {
    return (
        <>
            <Header>Dashboard</Header>

            <PageContent>
                <div className="p-6 text-gray-900 dark:text-gray-100">
                    {`You're logged in, ${sharedProps().auth?.user?.first_name}!`}
                </div>
            </PageContent>
        </>
    );
};

// examples/laravel-10-vue/resources/js/nexus/(global)/(auth)/admin/dashboard/page.vue
<script setup>
import { sharedProps } from '@laravext/vue';

import Header from '@/components/Header.vue';
import PageContent from '@/components/PageContent.vue';

</script>
<template>
    <Header>Dashboard</Header>

    <PageContent>
        <div class="p-6 text-gray-900 dark:text-gray-100">You're logged in, {{ sharedProps().auth.user.first_name }}!
        </div>
    </PageContent>
</template>
<script>
</script>
