// starter-kits/react/resources/js/nexus/(app)/confirm-password/page.tsx
// Components
import { LoaderCircle } from 'lucide-react';
import { FormEventHandler } from 'react';

import InputError from '@/components/input-error';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useForm } from '@/hooks/use-form';
import AuthLayout from '@/layouts/auth-layout';
import { Head, urlIntended, visit } from '@laravext/react';
import axios from 'axios';

export default function ConfirmPassword() {
    const url = urlIntended();
    console.log(url);

    const { data, setData, processing, setProcessing, errors, setErrors } = useForm({
        password: '',
    });

    const submit: FormEventHandler = (e) => {
        e.preventDefault();
        setProcessing(true);

        axios
            .post('api/confirm-password', data)
            .then(() => {
                visit(url ?? route('home'));
            })
            .catch((error) => {
                console.log(error);
                setErrors(error.response.data.errors);
            })
            .finally(() => {
                setProcessing(false);
            });
    };

    return (
        <AuthLayout
            title="Confirm your password"
            description="This is a secure area of the application. Please confirm your password before continuing."
        >
            <Head title="Confirm password" />

            <form onSubmit={submit}>
                <div className="space-y-6">
                    <div className="grid gap-2">
                        <Label htmlFor="password">Password</Label>
                        <Input
                            id="password"
                            type="password"
                            name="password"
                            placeholder="Password"
                            autoComplete="current-password"
                            value={data.password}
                            autoFocus
                            onChange={(e) => setData('password', e.target.value)}
                        />

                        <InputError message={errors.password} />
                    </div>

                    <div className="flex items-center">
                        <Button className="w-full" disabled={processing}>
                            {processing && <LoaderCircle className="h-4 w-4 animate-spin" />}
                            Confirm password
                        </Button>
                    </div>
                </div>
            </form>
        </AuthLayout>
    );
}

// starter-kits/vue/resources/js/nexus/(app)/confirm-password/page.vue
<script setup lang="ts">
import InputError from '@/components/InputError.vue';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import AuthLayout from '@/layouts/AuthLayout.vue';
import { Head , visit } from '@laravext/vue3';
import { LoaderCircle } from 'lucide-vue-next';
import { useForm } from '@/composables/useForm';
import axios from 'axios';
import { inject } from 'vue';
const urlIntended = inject('$urlIntended') as any;

const { data, processing, setProcessing, errors, setErrors } = useForm({
    password: '',
});

const submit = () => {
    setProcessing(true);

    axios
        .post('api/confirm-password', data.value)
        .then(() => {
            visit(urlIntended() ?? route('home'));
        })
        .catch((error) => {
            console.log(error);
            setErrors(error.response.data.errors);
        })
        .finally(() => {
            setProcessing(false);
        });
};
</script>

<template>
    <AuthLayout title="Confirm your password" description="This is a secure area of the application. Please confirm your password before continuing.">
        <Head title="Confirm password" />

        <form @submit.prevent="submit">
            <div class="space-y-6">
                <div class="grid gap-2">
                    <Label htmlFor="password">Password</Label>
                    <Input
                        id="password"
                        type="password"
                        class="mt-1 block w-full"
                        v-model="data.password"
                        required
                        autocomplete="current-password"
                        autofocus
                    />

                    <InputError :message="errors.password" />
                </div>

                <div class="flex items-center">
                    <Button class="w-full" :disabled="processing">
                        <LoaderCircle v-if="processing" class="h-4 w-4 animate-spin" />
                        Confirm Password
                    </Button>
                </div>
            </div>
        </form>
    </AuthLayout>
</template>
