// examples/laravel-11-react/resources/js/nexus/(global)/(auth)/admin/companies/page.jsx
import React, { useEffect } from 'react';
import useState from "react-usestateref";
import Pagination from '@/components/Pagination';
import PrimaryButton from '@/components/PrimaryButton';
import { debounce } from 'lodash';
import DangerButton from '@/components/DangerButton';
import Header from '@/components/Header';
import Link from '@/components/Link';
import SecondaryButton from '@/components/SecondaryButton';
import PageContent from '@/components/PageContent';
import Loading from '@/components/Loading';
import { useTranslation } from 'react-i18next';
import axios from 'axios';
import Swal from 'sweetalert2';
import usePrivacy from '@/hooks/usePrivacy';


const Companies = () => {
    const { t } = useTranslation();
    const { setActive: setPrivacyActive, active: privacyIsActive, toggle: togglePrivacy } = usePrivacy();
    const [pagination, setPagination, paginationRef] = useState({
        data: [],
        meta: {},
        loading: true,
        page: 1,
        per_page: 10,
    });

    const [filters, setFilters, filtersRef] = useState({
        search: '',
    });

    const fetchResources = () => {
        setPagination(prevState => ({ ...prevState, loading: true }));

        axios
            .get('/api/companies', {
                params: {
                    page: paginationRef.current.page,
                    per_page: paginationRef.current.per_page,
                    search: filtersRef.current.search ?? '',
                    include: 'team'
                },
            })
            .then(response => {
                setPagination(prevState => ({
                    ...prevState,
                    data: response.data.data,
                    meta: response.data.meta,
                    loading: false,
                }));
            })
            .catch(error => {
                console.error(error);
                setPagination(prevState => ({ ...prevState, loading: false }));
            });
    }

    const destroyResource = id => {
        Swal.fire({
            title: t('Are you sure?'),
            icon: 'warning',
            confirmButtonText: t('Yes, delete it!'),
            cancelButtonText: t('No, cancel!'),
            confirmButtonColor: '#d33',
            cancelButtonColor: '#3085d6',
            showCancelButton: true,
            showCloseButton: true,
        }).then(result => {
            if (result.isConfirmed) {
                axios
                    .delete(`/api/companies/${id}`)
                    .then(() => {
                        fetchResources();
                        Swal.fire(t('Record deleted!'), t('The company has been deleted.'), 'success');
                    })
                    .catch(error => {
                        console.error(error);
                        Swal.fire(t('Error!'), t('An error occurred while deleting the company.'), 'error');
                    });
            }
        });
    };

    const debouncedFetchResources = debounce(() => {
        pagination.page = 1;

        fetchResources();
    }, 1000);

    useEffect(() => {
        fetchResources();
    }, []);

    const paginateTo = ({ page, perPage }) => {
        setPagination(prevState => ({
            ...prevState,
            page,
            per_page: perPage,
        }));
        fetchResources();
    };

    return (
        <>
            <Header>{t('Companies')}</Header>

            <div className="mt-3 mx-4 flex justify-end space-x-2">
                <Link href="/admin/companies/create">
                    <PrimaryButton>{t('Create')}</PrimaryButton>
                </Link>
            </div>

            <PageContent>

                <Loading condition={pagination.loading} />

                <>
                    <div className="flex items-center justify-between mb-4">
                        <div className="flex items-center">
                            <input
                                type="text"
                                id="search"
                                value={filters.search}
                                onChange={(e) => {
                                    setFilters({ ...filters, search: e.target.value });
                                    console.log({ event: e.target.value })
                                    debouncedFetchResources();
                                }}
                                placeholder={t('Search')}
                                className="border border-gray-300 rounded px-3 py-2"
                            />
                        </div>
                    </div>

                    <table className={`min-w-full divide-y divide-gray-200 border my-4 ${pagination.loading ? 'opacity-50' : ''}`}>
                        <thead>
                            <tr>
                                <th className="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                                    ID
                                </th>
                                <th
                                    className="border-l px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                                    {t('Name')}
                                </th>
                                <th
                                    className="border-l px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                                    {t('Email')}
                                </th>
                                <th
                                    className="border-l px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                                    {t('Website')}
                                </th>
                                <th className="border-l w-96 px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                                    {t('Actions')}
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {pagination.data.map(resource => (
                                <tr
                                    key={resource.id}
                                    className="odd:bg-gray-100 odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 hover:bg-gray-200 hover:dark:bg-gray-700"
                                >
                                    <td className="border-t px-6 py-4 whitespace-no-wrap text-sm text-gray-900 w-28">
                                        <div className="text-sm leading-5 font-medium text-gray-900">{resource.id}</div>
                                    </td>
                                    <td className="border-t border-l px-6 py-4 whitespace-no-wrap">
                                        <div className="text-sm leading-5 font-medium text-gray-900">
                                            {resource.name}
                                        </div>
                                    </td>
                                    <td className="border-t border-l px-6 py-4 whitespace-no-wrap">
                                        <div className="text-sm leading-5 text-gray-900">
                                            {privacyIsActive ? '***@***' : resource.email}
                                        </div>
                                    </td>
                                    <td className="border-t border-l px-6 py-4 whitespace-no-wrap">
                                        <div className="text-sm leading-5 text-gray-900">
                                            {resource.website && <Link className="text-blue-600" href={resource.website}>
                                                {resource.website}
                                            </Link>}
                                            {(!resource.website) && <span>--</span>}
                                        </div>
                                    </td>
                                    <td className="border-t border-l px-6 py-4 whitespace-no-wrap text-right text-sm leading-5 font-medium space-x-2">
                                        <Link href={`/admin/companies/${resource.id}`}>
                                            <PrimaryButton>{t('Show')}</PrimaryButton>
                                        </Link>
                                        <Link href={`/admin/companies/${resource.id}/edit`}>
                                            <SecondaryButton>{t('Edit')}</SecondaryButton>
                                        </Link>
                                        <DangerButton onClick={() => destroyResource(resource.id)} className="hover:text-red-900">
                                            {t('Delete')}
                                        </DangerButton>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>

                    {!pagination.loading && <Pagination onPaginateTo={paginateTo} pagination={pagination} />}
                </>

            </PageContent >
        </>
    );
};

export default Companies;

// examples/laravel-10-vue/resources/js/nexus/(global)/(auth)/admin/companies/page.vue
<script setup>
import { onMounted, reactive, ref, inject } from 'vue';
import Pagination from '@/components/Pagination.vue';
import { debounce } from 'lodash';
import DangerButton from '@/components/DangerButton.vue';
import Header from '@/components/Header.vue';
import Link from '@/components/Link.vue';
import PrimaryButton from '@/components/PrimaryButton.vue';
import SecondaryButton from '@/components/SecondaryButton.vue';
import PageContent from '@/components/PageContent.vue';
import Loading from '@/components/Loading.vue';
import { privacy } from '@/composables/usePrivacy';
const swal = inject('$swal')
const pagination = reactive({
    data: [],
    meta: {},
    loading: true,
    page: 1,
    per_page: 10
});

const filters = reactive({
    search: '',
});

const paginateTo = ({ page, perPage }) => {
    pagination.page = page;
    pagination.per_page = perPage;

    fetchResources();
};

const fetchResources = () => {
    pagination.loading = true;

    axios.get('/api/companies', {
        params: {
            page: pagination.page,
            per_page: pagination.per_page,
            search: filters.search,
        },
    })
        .then(response => {
            pagination.data = response.data.data;
            pagination.meta = response.data.meta;
            pagination.loading = false;
        })
        .catch(error => {
            console.error(error);
            pagination.loading = false;
        });
};

const destroyResource = (id) => {
    swal({
        title: 'Are you sure?',
        icon: 'warning',
        confirmButtonText: 'Yes, delete it!',
        cancelButtonText: 'No, cancel!',
        confirmButtonColor: '#d33',
        cancelButtonColor: '#3085d6',
        showCancelButton: true,
        showCloseButton: true,

    })
        .then((result) => {
            if (result.isConfirmed) {
                axios.delete(`/api/companies/${id}`)
                    .then(() => {
                        fetchResources();
                        swal('Deleted!', 'The company has been deleted.', 'success');
                    })
                    .catch(error => {
                        console.error(error);
                        swal('Error!', 'An error occurred while deleting the company.', 'error');
                    });
            }
        });
}

const debouncedFetchResources = debounce(() => {
    pagination.page = 1;

    fetchResources();
}, 1000);

onMounted(async () => {
    fetchResources();
});

</script>
<template>
    <Header>Companies</Header>

    <div class="mt-3 mx-4 flex justify-end space-x-2">
        <Link routeName="admin.companies.create">
        <PrimaryButton>Create</PrimaryButton>
        </Link>
    </div>

    <PageContent>
        <Loading v-if="pagination.loading"  />

        <div class="flex items-center justify-between mb-4">
            <div class="flex items-center">

                <input type="text" id="search" v-model="filters.search" placeholder="Search"
                    class="border border-gray-300 rounded px-3 py-2" @input="debouncedFetchResources" />
            </div>
            <div class="flex items-center">
            </div>
        </div>


        <table :class="{ 'opacity-50': pagination.loading }" class="min-w-full divide-y divide-gray-200 border my-4">
            <thead>
                <th
                    class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                    ID
                </th>
                <th
                    class="border-l px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                    Name
                </th>
                <th
                    class="border-l px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                    Email
                </th>
                <th
                    class="border-l px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                    Website
                </th>
                <th
                    class="border-l w-96 px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                    Actions
                </th>
            </thead>
            <tbody>
                <tr class="odd:bg-gray-100 odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 hover:bg-gray-200 hover:dark:bg-gray-700"
                    v-for="resource in pagination.data" :key="resource.id">
                    <td class="border-t border-l px-6 py-4 whitespace-no-wrap text-sm text-gray-900 w-28">
                        <div class="text-sm leading-5 font-medium text-gray-900">
                            {{ resource.id }}
                        </div>
                    </td>
                    <td class="border-t border-l px-6 py-4 whitespace-no-wrap">
                        <div class="text-sm leading-5 font-medium text-gray-900">
                            {{ resource.name }}
                        </div>
                    </td>
                    <td class="border-t border-l px-6 py-4 whitespace-no-wrap">
                        <div class="text-sm leading-5 text-gray-900">
                            {{ privacy.active ? '***@***' : resource.email }}
                        </div>
                    </td>
                    <td class="border-t border-l px-6 py-4 whitespace-no-wrap">
                        <div class="text-sm leading-5 text-gray-900">
                            <Link v-if="resource.website" class="text-blue-600" :href="resource.website" >
                            {{ resource.website }}
                            </Link>
                            <span v-else>--</span>
                        </div>
                    </td>
                    <td
                        class="border-t border-l px-6 py-4 whitespace-no-wrap text-right text-sm leading-5 font-medium space-x-2">
                        <Link :href="`/admin/companies/${resource.id}/edit`">
                        <SecondaryButton>Edit</SecondaryButton>
                        </Link>
                        <DangerButton @click="destroyResource(resource.id)" class="hover:text-red-900">
                            Delete</DangerButton>
                    </td>
                </tr>
            </tbody>
        </table>

        <Pagination v-if="!pagination.loading" @paginate-to="paginateTo" :pagination="pagination ?? {}" />
    </PageContent>
</template>
<style scoped></style>
