// examples/laravel-11-vue/resources/js/nexus/(global)/(auth)/admin/companies/{company}/edit/page.vue
<script setup>
import Header from '@/components/Header.vue';
import Loading from '@/components/Loading.vue';
import PageContent from '@/components/PageContent.vue';
import { routeParams } from '@laravext/vue';
import axios from 'axios';
import { reactive, onMounted, inject } from 'vue';
import DangerButton from '@/components/DangerButton.vue';
import { useI18n } from 'vue-i18n';
import PrimaryButton from '@/components/PrimaryButton.vue';
import Link from '@/components/Link.vue';
const { t } = useI18n();

const swal = inject('$swal')

// Reactive form state
const form = reactive({
    data: {
        name: '',
        email: '',
        website: '',
    },
    errors: [],
    loading: true,
});

// Fetch company data on component mount
onMounted(() => {
    form.loading = true;
    axios.get(`/api/companies/${routeParams().company}`)
        .then(response => {
            form.data = response.data;
            form.loading = false;
        })
        .catch(() => {
            swal(t('Error!'), 'Failed to load company data.', 'error');
            form.loading = false;
        });
});

// Update team information
const updateResource = () => {
    form.errors = {};

    const data = {
        name: form.data.name,
        email: form.data.email,
        website: form.data.website,
    };

    return axios.put(`/api/companies/${routeParams().company}`, data)
        .then(() => {
            swal(t('Record updated!'), t('The company has been updated.'), 'success').then(() => {
                window.location.href = route('admin.companies');
            });
        })
        .catch(() => {
            swal(t('Error!'), t('An error occurred while updating the company.'), 'error');
        });
};

const destroyResource = (id) => {
    swal({
        title: t('Are you sure?'),
        icon: 'warning',
        confirmButtonText: t('Yes, delete it!'),
        cancelButtonText: t('No, cancel!'),
        confirmButtonColor: '#d33',
        cancelButtonColor: '#3085d6',
        showCancelButton: true,
        showCloseButton: true,

    })
        .then((result) => {
            if (result.isConfirmed) {
                axios.delete(`/api/companies/${id}`)
                    .then(() => {
                        swal(t('Record deleted!'), t('The company has been deleted.'), 'success').then(() => {
                            window.location.href = '/admin/companies';
                        });
                    })
                    .catch(error => {
                        console.error(error);
                        swal(t('Error!'), t('An error occurred while deleting the company.'), 'error');
                    });
            }
        });
}

</script>
<template>
    <Header>{{ form.loading ? $t('Loading...') : `${$t('Edit company')} #${routeParams().company} - ${form.data.name}` }}</Header>
    <div class="mt-3 mx-4 flex justify-end space-x-2">
        <Link :href="`/admin/companies/${routeParams().company}`">
            <PrimaryButton>{{ $t('Show') }}</PrimaryButton>
        </Link>
        <DangerButton @click="destroyResource(routeParams().company)" class="hover:text-red-900">{{ $t('Delete') }}</DangerButton>
    </div>
    <Loading v-if="form.loading" />
    <PageContent v-else>
        <FormKit :submit-label="$t('Save')" @submit="updateResource" type="form">
            <div class="flex justify-start space-x-4">
                <FormKit validation-visibility="live" type="text" name="name" validation="length:2,200" required id="name"
                    :label="$t('Name')" :placeholder="`“${$t('The Beatles')}”`" v-model="form.data.name" />
    
                <FormKit validation-visibility="live" type="email" name="email" validation="email" required id="email"
                    :label="$t('Email')" :placeholder="`“${$t('cool-email@email.com')}”`" v-model="form.data.email" />

                    <FormKit validation-visibility="live" type="text" name="website" validation="url" required id="website"
                    :label="$t('Website')" :placeholder="`“${$t('cool-website.com')}”`" v-model="form.data.website" />

            </div>
        </FormKit>
    </PageContent>
</template>

// examples/laravel-11-react/resources/js/nexus/(global)/(auth)/admin/companies/{company}/edit/page.jsx
import Header from '@/components/Header';
import Loading from '@/components/Loading';
import PageContent from '@/components/PageContent';
import { routeParams } from '@laravext/react';
import axios from 'axios';
import { useEffect } from 'react';
import DangerButton from '@/components/DangerButton'
import PrimaryButton from '@/components/PrimaryButton';
import Link from '@/components/Link';
import { useTranslation } from 'react-i18next';
import Swal from 'sweetalert2';
import useStateRef from 'react-usestateref';
import usePrivacy from '@/hooks/usePrivacy';
import FormSaveButton from '@/components/FormSaveButton';

export default () => {
    const { t } = useTranslation();

    const { setActive: setPrivacyActive, active: privacyIsActive, toggle: togglePrivacy } = usePrivacy();

    const [form, setForm, formRef] = useStateRef({
        data: {},
        errors: [],
        loading: true,
        submitting: false,
    });

    useEffect(() => {
        axios.get(`/api/companies/${routeParams().company}`)
            .then(response => {
                setForm(prevState => ({
                    ...prevState, data: response.data, loading: false
                }));
            });
    }, []);


    const destroyResource = id => {
        Swal.fire({
            title: t('Are you sure?'),
            icon: 'warning',
            confirmButtonText: t('Yes, delete it!'),
            cancelButtonText: t('No, cancel!'),
            confirmButtonColor: '#d33',
            cancelButtonColor: '#3085d6',
            showCancelButton: true,
            showCloseButton: true,
        }).then(result => {
            if (result.isConfirmed) {
                axios
                    .delete(`/api/companies/${id}`)
                    .then(() => {
                        Swal.fire(t('Record deleted!'), t('The company has been deleted.'), 'success').then(() => {
                            window.location.href = '/admin/companies';
                        });
                    })
                    .catch(error => {
                        console.error(error);
                        Swal.fire(t('Error!'), t('An error occurred while deleting the company.'), 'error');
                    });
            }
        });
    };

    const updateResource = () => {
        setForm(prevState => ({ ...prevState, submitting: true }));

        const data = {
            name: form.data.name,
            email: form.data.email,
            website: form.data.website,
        };

        return axios.put(`/api/companies/${routeParams().company}`, data)
            .then(() => {
                setForm(prevState => ({ ...prevState, submitting: false }));
                Swal.fire(t('Record updated!'), t('The company has been updated.'), 'success').then(() => {
                    // window.location.href = route('admin.companies');
                });
            })
            .catch(() => {
                setForm(prevState => ({ ...prevState, submitting: false }));
                Swal.fire(t('Error!'), t('An error occurred while updating the company.'), 'error');
            });
    };

    return (
        <>
            <Header>{form.loading ? t('Loading...') : `#${form.data.id} - ${form.data.name}`}</Header>
            <div className="mt-3 mx-4 flex justify-end space-x-2">
                <Link href={`/admin/companies/${routeParams().company}`}>
                    <PrimaryButton>{t('Show')}</PrimaryButton>
                </Link>
                <DangerButton onClick={() => destroyResource(routeParams().company)} className="hover:text-red-900">{t('Delete')}</DangerButton >
            </div >
            {form.loading ? <Loading /> :
                <PageContent>
                    <FormSaveButton disabled={form.submitting} loading={form.submitting} onClick={() => {
                        if(form.submitting){
                            return;
                        }

                        updateResource();


                    }}>{t('Save')}</FormSaveButton>
                </PageContent>
            }
        </>
    );
}
