// examples/laravel-10-vue/resources/js/components/DropdownButton.vue
<script setup>

</script>

<template>
    <button
        class="block w-full px-4 py-2 text-start text-sm leading-5 text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800 focus:outline-none focus:bg-gray-100 dark:focus:bg-gray-800 transition duration-150 ease-in-out">
        <slot />
    </button>
</template>

// examples/laravel-11-react/resources/js/components/DropdownButton.jsx
export default ({ children, className = '', ... props }) => {
    return (
        <button className={"block w-full px-4 py-2 text-start text-sm leading-5 text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800 focus:outline-none focus:bg-gray-100 dark:focus:bg-gray-800 transition duration-150 ease-in-out " + className}
            {...props}
        >
            {children}
        </button>
    );
};
