// examples/laravel-11-vue/resources/js/components/Fa.vue
<script setup>

import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import { faPlus, faTrash, faEye, faEyeSlash, faCheckCircle, faClock } from '@fortawesome/free-solid-svg-icons'
// import { fas } from '@fortawesome/free-solid-svg-icons'

// Add all solid icons to the library so they can be used
library.add(faPlus, faTrash, faEye, faEyeSlash, faCheckCircle, faClock )

// In case you want to add all icons from the solid style, which is not recommended
// library.add(fas)

const props = defineProps({
    icon: {
        type: [Object, Array],
        required: true,
    },
    size: {
        type: String,
        default: '1x',
    },
    class: {
        type: String,
        default: '',
    },
});

</script>
<template>
    <FontAwesomeIcon :icon="icon" :size="size" :class="class" />
</template>

// examples/laravel-11-react/resources/js/components/Fa.jsx
import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faPlus, faTrash, faEye, faEyeSlash, faCheckCircle, faClock, faBookmark as faSolidBookmark } from '@fortawesome/free-solid-svg-icons'
import { faBookmark as faRegularBookmark} from '@fortawesome/free-regular-svg-icons'

// Add all solid icons to the library so they can be used
library.add(faPlus, faTrash, faEye, faEyeSlash, faCheckCircle, faClock, faSolidBookmark, faRegularBookmark )

export default function Fa({ icon, className='', size = '1x', ...props }) {
  return <FontAwesomeIcon className={className} size={size} icon={icon} {...props} />;
}
